import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import AuthScreen from '../components/Auth';
import Login from '../components/Auth';
import Confirmation from '../components/Confirmation';
import QuoteRequestForm from '../components/QuoteRequestForm';
import Register from '../components/Register';

export default function Home() {
	const [loggedUser, setLoggedUser] = useState(false);
	const [userEmail, setUserEmail] = useState('');

	const loginUser = () => {
		setLoggedUser(true);
		setUserEmail('testuser@test.com');
	};
	const logoutUser = () => {
		setLoggedUser(false);
		setUserEmail('');
	};
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<section className='py-20'>
					<div className='container'>
						<div className='flex'>
							<div className='w-full md:w-2/3'>
								<AuthScreen
									loginUser={loginUser}
									userEmail={userEmail}
									logoutUser={logoutUser}
								/>

								{/* <Register /> */}
								<div>
									<QuoteRequestForm loggedUser={loggedUser} />
								</div>
								<div>
									<Confirmation loggedUser={loggedUser} />
								</div>
							</div>
						</div>
					</div>
				</section>
			</main>
		</div>
	);
}
